name: "EasyAnnouncement"
author: "HakanBabus"
version: "1.0.1"
api: ["4.0.0", "5.0.0"]
main: HakanBabus\EasyAnnouncement\EasyAnnouncement

permissions:
  easyannouncement.command:
    default: op
